# Generated by Django 4.2.9 on 2024-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=100)),
                ('joined_at', models.DateField()),
                ('password', models.CharField(max_length=48)),
            ],
        ),
    ]
